# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mason Cereo
title: Data Scientist
email: macereo@gmail.com
website: macereo.github.io/ds-portfolio/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  macereo
instagram_username: macheerio
linkedin_username: mcereo
facebook_username: masoncereo

# Additional icon links
additional_links:
- title: portfolio
  icon: fas fa-globe
  url: https://github.com/macereo/ds-portfolio

#- title: facebook
#   icon: fa brands fa-facebook
#   url: https://www.facebook.com/masoncereo

#- title: email me
#  icon: fa solid fa-envelope
#  url: mailto: macereo@gmail.com

# About Section
about_title: About Me
about_profile_image: images/graphic-novel-me-sq.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there, and welcome to my Digital Portfolio! I'm a Data Scientist and 15-year Army Veteran ðŸ«¡ with a passion for getting it right, doing good, and leaving a positive impact. 

  I began my tech journey as a Network Specialist (in the Army that's kind of a hybrid network engineer/admin/IT helpdesk), providing network communications and network connectivity at a regional scale and helping folks troubleshoot issues (usually turning things on and off, am I right?ðŸ‘€). Although I intended to pursue higher education after high school, I struggled to find a subject that truly captured my interest--until 8 years later when my partner took a tour where some folks were using GIS. She came home that day and told me all about how data was being used in that office, and the rest is history--I was hooked.  

  I approach everything with a growth mindset, I'm results-oriented (thanks, Army!), and I have a work-ethic that's difficult to match. I carefully analyze (and let's be honest, I sometimes over-analyze ðŸ˜…) obstacles, and love collaborating and brainstorming with others, but I'm equally confident taking initiative and working independently (just give me some headphones ðŸŽ§). 

  When I don't have numbers swirling about my head, you can find me adventuring ðŸ—º with my partner, daughter, and two pups ðŸ‘¨â€ðŸ‘©â€ðŸ‘§ðŸ•â€ðŸ¦ºðŸ¦®. I also love rugby ðŸ‰, reading ðŸ“š, video games ðŸŽ®, and throwing down weights at the gym ðŸ‹ï¸â€â™‚ï¸. 

  
  quote: >
    I'm just getting started with my official Digital Portfolio. It's a work in progress as I transition from the Army. Stay tuned and check back for more projects!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Current Projects
        link: github.com/macereo/ds-portfolio
        description: | # this will include new lines to allow paragraphs
          Description here

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Google
        sub_title: EDIT LATER
        caption: Aug 2024 - Nov 2024
        description: | # this will include new lines to allow paragraphs
            Description about Fellowship. 
      - layout: left
        title: United States Army
        sub_title: EDIT LATER
        caption: Mar 2020 - Present
        description: |
            Description about current role, and headed out of the Army
      - layout: left
        title: United States Army
        sub_title: EDIT LATER
        caption: Nov 2015 - Mar 2020
        description: |
            Description about previous role. 
      - layout: left
        title: United States Army
        sub_title: EDIT LATER
        caption: Nov 2009 - Nov 2015
        description: | 
            Description about network role. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2010 - 2013
        sub_title: BS Geographic Information Science
        description: | # this will include new lines to allow paragraphs
          Describe experience at ASU

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
